### ISSUE TITLE
possible to post an example ios that links properly against this?

### ISSUE THREAD

**Issue by ofZach** [PaulWagener/mapnik-ios-framework#1]
first, thanks so much for this great build script / configuration -- I was able to get everything built pretty easily.  

I'm trying to link these libraries now against simulator or device and I'm getting all kinds of linker errors that seem to relate to libstdc++.  I've adjusted quite a bit of my build settings ( to not use the libc++ for example since I see you've adjusted that for boost) but I can't seem to get it right.   

It would definitely help alot to have an example project if you have something that links properly with this.

**Comment by PaulWagener** [comment]
I've tested the example project on my device, it should display a picture of the world. The simulator fails for now due to something in pixman.

Are you trying to get OpenStreetMap to work? Because I've made progress with that as well (though stuck at the moment).

**Comment by gstf** [comment]
Use -DPIXMAN_NO_TLS for simulator to make it work.

**Comment by wibrahim** [comment]
I tried everything and I cant seem to get this example to build, Im still getting the linker errors even tho I did set my build settings to not use libc++ ... any help on that ?

**Comment by PaulWagener** [comment]
Can you share the output of the linker?

**Comment by wibrahim** [comment]
well I'm actually getting a 108 linker error. The first two are related to mapnik:

Undefined symbols for architecture i386:
  "mapnik::load_map_string(mapnik::Map&, std::string const&, bool, std::string)", referenced from:
      -[ViewController updateMethod:] in ViewController.o
  "mapnik::Map::Map(int, int, std::string const&)", referenced from:
      -[ViewController updateMethod:] in ViewController.o

And then the rest are related to std:

 "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const", referenced from:
      boost::filesystem::path::m_parent_path_end() const in libboost_filesystem.a(path.o)
      boost::filesystem::path::filename() const in libboost_filesystem.a(path.o)
      boost::filesystem::path::m_path_iterator_decrement(boost::filesystem::path::iterator&) in libboost_filesystem.a(path.o)

This is the output from the Mapnik-Example generated by using the make script included in the mapnik-ios-framework. 
I actually went an extra mile and I installed mapnik using homebrew with all the dependencies and the binding with cairo/cairomm, all the libraries were built for i386 and x86_64, which I was able to build in xcode with no errors at all but when I run the project in the simulator I get a security exception:

Symbol not found: ___CFObjCIsCollectable   Referenced from: /System/Library/Frameworks/Security.framework/Versions/A/Security   Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation  in /System/Library/Frameworks/Security.framework/Versions/A/Security

Which I was able to trace back to the cairo libs been included. I did incorporate the cairo.patch and cairomm.patch from the mapnik-ios-framework into the brew script to install cairo and cairomm libraries.

**Comment by wibrahim** [comment]
Ah just to note that I had to change the configure.ac inside the pixman library to use AC_CONFIG_HEADERS instead of AM_CONFIG_HEADERS also the script failed building the pixman tests which I just ignored, hopefully this is not the cause of my linker problems ?

**Comment by wibrahim** [comment]
Also when I built mapnik using homebrew without cairo bindings, since they were giving me the security exception,  and ran the project in the simulator I got the error:  

error: Could not create datasource. No plugin found for type 'shape' (searched in: )

**Comment by gstf** [comment]
@wibrahim: I were able to build with some changes. Don't know if you have the same problems.
Check them out if you want to (https://github.com/gstf/mapnik-ios-framework)

**Comment by wibrahim** [comment]
@gstf thanks, I cloned your code and building it at the moment. Ill keep you posted.
@PaulWagener here is the full linker output from xcode for mapnik-ios-framework <a href="https://gist.github.com/wibrahim/5445337.js">gist-5445337</a>

**Comment by wibrahim** [comment]
@gstf great it works !!! thanks for your fixes, the only change I had to make was to change pixman/configure.ac and replace the AM_HEADER_CONFIG with AC_HEADER_CONFIG

**Comment by PaulWagener** [comment]
@gstf I've added you're changes to my repo as well. Thanks for fixing it!

**Comment by gstf** [comment]
@PaulWagener Great. Thanks for your hard groundwork.

**Comment by wibrahim** [comment]
is anyone here familiar with this issue: https://github.com/mapnik/mapnik-support/issues/12
