### ISSUE TITLE
libpng git repo relocated

### ISSUE THREAD

**Issue by rghosh0** [PaulWagener/mapnik-ios-framework#4]
Hi,
FYI, the libpng git repository has been relocated to:
git://git.code.sf.net/p/libpng/code

I had to change the .gitmodules file to point to the new repo, before running make.

**Comment by Whirlwind** [comment]
I found the git repository in .gitmoudules is available. It not need to change it.

**Comment by rghosh0** [comment]
OK, now both git urls seem to be working.  2 months ago, the url you're using in .gitmodules didn't work, and make failed, which is what prompted me to switch urls.  I've seen other people having issues involving an apparent change in the url (e.g. http://sourceforge.net/mailarchive/message.php?msg_id=30249039 ) but I guess it doesn't matter anymore if the repo has been restored.
